name: Github pull request data
description: Buildkite plugin designed to fetch pull request data from GitHub
author: https://github.com/ddepaoli3
requirements:
  - curl
  - jq
configuration:
  properties:
    token:
      type: string
  additionalProperties: false

